package com.bank.bian.tradingbookmanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Trading Book Management
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Markets and Treasury
 * Functional Pattern: Manage
 * Asset Type:         Trading Book
 * Control Record:     Trading Book Management Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Trading Book Management — BIAN Semantic API")
                .description("Service Domain 'Trading Book Management' (Manage pattern) "
                        + "operating on the 'Trading Book Management Plan' control record.")
                .version("0.1.0"));
    }
}
